import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Mulish } from "next/font/google";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

const mulish=Mulish({
      weights: ["300", "400", "500", "600", "700"],
      subsets: ["latin"],
      display: "swap",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
